#开发环境配置

#Tomcat配置
server:
  port: 9000
  servlet:
    context-path: /plansolve
    session:
      cookie:
        name: SESSIONID
        max-age: 2592000
  tomcat:
    uri-encoding: UTF-8

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3307/farm_test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    #username: root
    #password: root
    url: jdbc:mysql://rm-hp3b32jos339upm0xuo.mysql.huhehaote.rds.aliyuncs.com:3306/farm_test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: yhyapp
    password: YHY123qwe
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    # properties:
      # hibernate:
        # show_sql: true  # 打印SQL语句
        # format_sql: true  # 格式化SQL语句
        # use_sql_comments: true  # 增加注释信息，就知道语句对应的Entity类型了
        # generate_statistics: true # 统计信息，给出了每一步的耗时信息
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    cache: true
    encoding: UTF-8
    suffix: .html
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true

#数据缓存
cache:
  resources: spring.cache.ehcache.config=classpath:ehcache.xml

#项目访问地址
projectURL: "http://ping.nat100.top/plansolve"

#文件保存地址
file:
  fileRealPath: "D:/Cache/Farm/"
  fileUrlPath: "//ping.nat100.top/plansolve/file/"

#验证码服务
message:
  url: "http://service.winic.org/sys_port/gateway/index.asp"
  id: "pulansuo"
  pwd: "123qweQWE"

# 微信
wechat:
  miniAppId: "wx7525b3efcb4eaae4"
  miniAppSecret: "9e82c5d7d81604e809dc3d1ecf201f81"
  miniAppToken: ""
  miniAppAesKey: ""
  miniAppMsgDataFormat: ""
  mpAppId: "wx303aa0ea213b400d"
  mpAppSecret: "3c5cc946d6ecc9bb7b98658a5570a639"
  mpToken: "plansolve"
  appId: "wxb6cfa46502c3419f"
  mchId: "1523392121"
  mchKey: "D114138FD7EBC09A9D612E2F6A363657"
  keyPath: "/home/farm/wechat_mp_pay/apiclient_cert.p12"
  notifyUrl: "http://ping.nat100.top/plansolve/farm/order/pay/notify"

#开发者模式
development: true